# Generated by Django 2.0.4 on 2018-04-15 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='Dhoice',
        ),
    ]
